In [5]:
import numpy as np

In [22]:
table=np.ones((5,5),dtype=int)
table[1:-1, 1:-1]=np.zeros((3,3),dtype=int)
table[2,2]=9
print(table)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
